// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer_caps_cache.sql

package dbpg

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const getIndexerCapsCache = `-- name: GetIndexerCapsCache :one
SELECT last_caps_json
FROM   indexer_health
WHERE  indexer_id = $1
LIMIT  1
`

func (q *Queries) GetIndexerCapsCache(ctx context.Context, indexerID string) (pqtype.NullRawMessage, error) {
	row := q.db.QueryRowContext(ctx, getIndexerCapsCache, indexerID)
	var last_caps_json pqtype.NullRawMessage
	err := row.Scan(&last_caps_json)
	return last_caps_json, err
}

const updateIndexerCapsCache = `-- name: UpdateIndexerCapsCache :exec
UPDATE indexer_health
SET    last_caps_json = $1
WHERE  indexer_id     = $2
`

type UpdateIndexerCapsCacheParams struct {
	LastCapsJson pqtype.NullRawMessage `json:"last_caps_json"`
	IndexerID    string                `json:"indexer_id"`
}

func (q *Queries) UpdateIndexerCapsCache(ctx context.Context, arg UpdateIndexerCapsCacheParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexerCapsCache, arg.LastCapsJson, arg.IndexerID)
	return err
}
