// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbpg

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Prefix     string       `json:"prefix"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type Indexer struct {
	ID             string          `json:"id"`
	Kind           string          `json:"kind"`
	Name           string          `json:"name"`
	Enabled        bool            `json:"enabled"`
	Priority       int32           `json:"priority"`
	ConfigJson     json.RawMessage `json:"config_json"`
	CategoriesJson json.RawMessage `json:"categories_json"`
	TagsJson       json.RawMessage `json:"tags_json"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	ProxyID        sql.NullString  `json:"proxy_id"`
}

type IndexerHealth struct {
	IndexerID     string                `json:"indexer_id"`
	Status        string                `json:"status"`
	LastCheckedAt time.Time             `json:"last_checked_at"`
	LastSuccessAt sql.NullTime          `json:"last_success_at"`
	LatencyMs     sql.NullInt32         `json:"latency_ms"`
	LastError     string                `json:"last_error"`
	LastCapsJson  pqtype.NullRawMessage `json:"last_caps_json"`
}

type Proxy struct {
	ID         string          `json:"id"`
	Kind       string          `json:"kind"`
	Name       string          `json:"name"`
	Enabled    bool            `json:"enabled"`
	ConfigJson json.RawMessage `json:"config_json"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type ScheduledJob struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	Schedule   string          `json:"schedule"`
	LastRunAt  sql.NullTime    `json:"last_run_at"`
	NextRunAt  sql.NullTime    `json:"next_run_at"`
	Paused     bool            `json:"paused"`
	Payload    json.RawMessage `json:"payload"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
	Enabled    bool            `json:"enabled"`
	LastStatus string          `json:"last_status"`
	LastError  string          `json:"last_error"`
}

type SchemaMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	Role         string         `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
