// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbpg

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ApiKey struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Prefix     string       `json:"prefix"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type ScheduledJob struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	Schedule   string          `json:"schedule"`
	LastRunAt  sql.NullTime    `json:"last_run_at"`
	NextRunAt  sql.NullTime    `json:"next_run_at"`
	Paused     bool            `json:"paused"`
	Payload    json.RawMessage `json:"payload"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
	Enabled    bool            `json:"enabled"`
	LastStatus string          `json:"last_status"`
	LastError  string          `json:"last_error"`
}

type SchemaMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	Role         string         `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
