// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package dbpg

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countMovies = `-- name: CountMovies :one
SELECT COUNT(*) FROM movies WHERE deleted_at IS NULL
`

func (q *Queries) CountMovies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMovies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
    id, title, year, imdb_id, tmdb_id, tvdb_id,
    overview, genres, runtime, rating,
    backdrop_path, poster_path,
    metadata_provider, last_search_at, monitoring_status,
    created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12,
    $13, $14, $15,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at
`

type CreateMovieParams struct {
	ID               string          `json:"id"`
	Title            string          `json:"title"`
	Year             int32           `json:"year"`
	ImdbID           sql.NullString  `json:"imdb_id"`
	TmdbID           sql.NullString  `json:"tmdb_id"`
	TvdbID           sql.NullString  `json:"tvdb_id"`
	Overview         string          `json:"overview"`
	Genres           json.RawMessage `json:"genres"`
	Runtime          int32           `json:"runtime"`
	Rating           float32         `json:"rating"`
	BackdropPath     string          `json:"backdrop_path"`
	PosterPath       string          `json:"poster_path"`
	MetadataProvider string          `json:"metadata_provider"`
	LastSearchAt     sql.NullTime    `json:"last_search_at"`
	MonitoringStatus string          `json:"monitoring_status"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.ID,
		arg.Title,
		arg.Year,
		arg.ImdbID,
		arg.TmdbID,
		arg.TvdbID,
		arg.Overview,
		arg.Genres,
		arg.Runtime,
		arg.Rating,
		arg.BackdropPath,
		arg.PosterPath,
		arg.MetadataProvider,
		arg.LastSearchAt,
		arg.MonitoringStatus,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMovieFile = `-- name: CreateMovieFile :one
INSERT INTO movie_files (
    id, movie_id, file_path, size, quality, format,
    media_info, file_date, date_added,
    created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, movie_id, file_path, size, quality, format, media_info, file_date, date_added, created_at, updated_at, deleted_at
`

type CreateMovieFileParams struct {
	ID        string          `json:"id"`
	MovieID   string          `json:"movie_id"`
	FilePath  string          `json:"file_path"`
	Size      int64           `json:"size"`
	Quality   string          `json:"quality"`
	Format    string          `json:"format"`
	MediaInfo json.RawMessage `json:"media_info"`
	FileDate  sql.NullTime    `json:"file_date"`
	DateAdded time.Time       `json:"date_added"`
}

func (q *Queries) CreateMovieFile(ctx context.Context, arg CreateMovieFileParams) (MovieFile, error) {
	row := q.db.QueryRowContext(ctx, createMovieFile,
		arg.ID,
		arg.MovieID,
		arg.FilePath,
		arg.Size,
		arg.Quality,
		arg.Format,
		arg.MediaInfo,
		arg.FileDate,
		arg.DateAdded,
	)
	var i MovieFile
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.FilePath,
		&i.Size,
		&i.Quality,
		&i.Format,
		&i.MediaInfo,
		&i.FileDate,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRootFolder = `-- name: CreateRootFolder :one
INSERT INTO root_folders (
    id, path, free_space, unmapped_count,
    created_at, updated_at
)
VALUES (
    $1, $2, $3, $4,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, path, free_space, unmapped_count, created_at, updated_at, deleted_at
`

type CreateRootFolderParams struct {
	ID            string `json:"id"`
	Path          string `json:"path"`
	FreeSpace     int64  `json:"free_space"`
	UnmappedCount int32  `json:"unmapped_count"`
}

func (q *Queries) CreateRootFolder(ctx context.Context, arg CreateRootFolderParams) (RootFolder, error) {
	row := q.db.QueryRowContext(ctx, createRootFolder,
		arg.ID,
		arg.Path,
		arg.FreeSpace,
		arg.UnmappedCount,
	)
	var i RootFolder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FreeSpace,
		&i.UnmappedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMovieFilesByMovieID = `-- name: DeleteMovieFilesByMovieID :exec
UPDATE movie_files SET deleted_at = CURRENT_TIMESTAMP WHERE movie_id = $1
`

func (q *Queries) DeleteMovieFilesByMovieID(ctx context.Context, movieID string) error {
	_, err := q.db.ExecContext(ctx, deleteMovieFilesByMovieID, movieID)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMovie(ctx context.Context, id string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovieBYTVDBID = `-- name: GetMovieBYTVDBID :one
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE tvdb_id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMovieBYTVDBID(ctx context.Context, tvdbID sql.NullString) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieBYTVDBID, tvdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovieByIMDBID = `-- name: GetMovieByIMDBID :one
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE imdb_id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMovieByIMDBID(ctx context.Context, imdbID sql.NullString) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieByIMDBID, imdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovieByTMDBID = `-- name: GetMovieByTMDBID :one
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE tmdb_id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMovieByTMDBID(ctx context.Context, tmdbID sql.NullString) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieByTMDBID, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovieFile = `-- name: GetMovieFile :one
SELECT id, movie_id, file_path, size, quality, format, media_info, file_date, date_added, created_at, updated_at, deleted_at FROM movie_files WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMovieFile(ctx context.Context, id string) (MovieFile, error) {
	row := q.db.QueryRowContext(ctx, getMovieFile, id)
	var i MovieFile
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.FilePath,
		&i.Size,
		&i.Quality,
		&i.Format,
		&i.MediaInfo,
		&i.FileDate,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovieFileByPath = `-- name: GetMovieFileByPath :one
SELECT id, movie_id, file_path, size, quality, format, media_info, file_date, date_added, created_at, updated_at, deleted_at FROM movie_files WHERE file_path = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMovieFileByPath(ctx context.Context, filePath string) (MovieFile, error) {
	row := q.db.QueryRowContext(ctx, getMovieFileByPath, filePath)
	var i MovieFile
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.FilePath,
		&i.Size,
		&i.Quality,
		&i.Format,
		&i.MediaInfo,
		&i.FileDate,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRootFolder = `-- name: GetRootFolder :one
SELECT id, path, free_space, unmapped_count, created_at, updated_at, deleted_at FROM root_folders WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRootFolder(ctx context.Context, id string) (RootFolder, error) {
	row := q.db.QueryRowContext(ctx, getRootFolder, id)
	var i RootFolder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FreeSpace,
		&i.UnmappedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRootFolderByPath = `-- name: GetRootFolderByPath :one
SELECT id, path, free_space, unmapped_count, created_at, updated_at, deleted_at FROM root_folders WHERE path = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRootFolderByPath(ctx context.Context, path string) (RootFolder, error) {
	row := q.db.QueryRowContext(ctx, getRootFolderByPath, path)
	var i RootFolder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FreeSpace,
		&i.UnmappedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMovieFilesByMovieID = `-- name: ListMovieFilesByMovieID :many
SELECT id, movie_id, file_path, size, quality, format, media_info, file_date, date_added, created_at, updated_at, deleted_at FROM movie_files WHERE movie_id = $1 AND deleted_at IS NULL ORDER BY file_date DESC
`

func (q *Queries) ListMovieFilesByMovieID(ctx context.Context, movieID string) ([]MovieFile, error) {
	rows, err := q.db.QueryContext(ctx, listMovieFilesByMovieID, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MovieFile{}
	for rows.Next() {
		var i MovieFile
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.FilePath,
			&i.Size,
			&i.Quality,
			&i.Format,
			&i.MediaInfo,
			&i.FileDate,
			&i.DateAdded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE deleted_at IS NULL ORDER BY title ASC, year DESC
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Overview,
			&i.Genres,
			&i.Runtime,
			&i.Rating,
			&i.BackdropPath,
			&i.PosterPath,
			&i.MetadataProvider,
			&i.LastSearchAt,
			&i.MonitoringStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMoviesByMonitoringStatus = `-- name: ListMoviesByMonitoringStatus :many
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE monitoring_status = $1 AND deleted_at IS NULL ORDER BY title ASC
`

func (q *Queries) ListMoviesByMonitoringStatus(ctx context.Context, monitoringStatus string) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMoviesByMonitoringStatus, monitoringStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Overview,
			&i.Genres,
			&i.Runtime,
			&i.Rating,
			&i.BackdropPath,
			&i.PosterPath,
			&i.MetadataProvider,
			&i.LastSearchAt,
			&i.MonitoringStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMoviesByYear = `-- name: ListMoviesByYear :many
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies WHERE year = $1 AND deleted_at IS NULL ORDER BY title ASC
`

func (q *Queries) ListMoviesByYear(ctx context.Context, year int32) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMoviesByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Overview,
			&i.Genres,
			&i.Runtime,
			&i.Rating,
			&i.BackdropPath,
			&i.PosterPath,
			&i.MetadataProvider,
			&i.LastSearchAt,
			&i.MonitoringStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, path, free_space, unmapped_count, created_at, updated_at, deleted_at FROM root_folders WHERE deleted_at IS NULL ORDER BY path ASC
`

func (q *Queries) ListRootFolders(ctx context.Context) ([]RootFolder, error) {
	rows, err := q.db.QueryContext(ctx, listRootFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootFolder{}
	for rows.Next() {
		var i RootFolder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FreeSpace,
			&i.UnmappedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovies = `-- name: SearchMovies :many
SELECT id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at FROM movies
WHERE (title ILIKE $1 OR overview ILIKE $2)
AND deleted_at IS NULL
ORDER BY title ASC
LIMIT $3
OFFSET $4
`

type SearchMoviesParams struct {
	Title    string `json:"title"`
	Overview string `json:"overview"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, searchMovies,
		arg.Title,
		arg.Overview,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Overview,
			&i.Genres,
			&i.Runtime,
			&i.Rating,
			&i.BackdropPath,
			&i.PosterPath,
			&i.MetadataProvider,
			&i.LastSearchAt,
			&i.MonitoringStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMonitoringStatus = `-- name: SetMonitoringStatus :one
UPDATE movies
SET monitoring_status = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at
`

type SetMonitoringStatusParams struct {
	MonitoringStatus string `json:"monitoring_status"`
	ID               string `json:"id"`
}

func (q *Queries) SetMonitoringStatus(ctx context.Context, arg SetMonitoringStatusParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, setMonitoringStatus, arg.MonitoringStatus, arg.ID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteMovie = `-- name: SoftDeleteMovie :exec
UPDATE movies SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SoftDeleteMovie(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteMovie, id)
	return err
}

const softDeleteMovieFile = `-- name: SoftDeleteMovieFile :exec
UPDATE movie_files SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SoftDeleteMovieFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteMovieFile, id)
	return err
}

const softDeleteRootFolder = `-- name: SoftDeleteRootFolder :exec
UPDATE root_folders SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SoftDeleteRootFolder(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteRootFolder, id)
	return err
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title = COALESCE($1, title),
    year = COALESCE($2, year),
    overview = COALESCE($3, overview),
    genres = COALESCE($4, genres),
    runtime = COALESCE($5, runtime),
    rating = COALESCE($6, rating),
    backdrop_path = COALESCE($7, backdrop_path),
    poster_path = COALESCE($8, poster_path),
    monitoring_status = COALESCE($9, monitoring_status),
    last_search_at = COALESCE($10, last_search_at),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, title, year, imdb_id, tmdb_id, tvdb_id, overview, genres, runtime, rating, backdrop_path, poster_path, metadata_provider, last_search_at, monitoring_status, created_at, updated_at, deleted_at
`

type UpdateMovieParams struct {
	Title            sql.NullString        `json:"title"`
	Year             sql.NullInt32         `json:"year"`
	Overview         sql.NullString        `json:"overview"`
	Genres           pqtype.NullRawMessage `json:"genres"`
	Runtime          sql.NullInt32         `json:"runtime"`
	Rating           sql.NullFloat64       `json:"rating"`
	BackdropPath     sql.NullString        `json:"backdrop_path"`
	PosterPath       sql.NullString        `json:"poster_path"`
	MonitoringStatus sql.NullString        `json:"monitoring_status"`
	LastSearchAt     sql.NullTime          `json:"last_search_at"`
	ID               string                `json:"id"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, updateMovie,
		arg.Title,
		arg.Year,
		arg.Overview,
		arg.Genres,
		arg.Runtime,
		arg.Rating,
		arg.BackdropPath,
		arg.PosterPath,
		arg.MonitoringStatus,
		arg.LastSearchAt,
		arg.ID,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Overview,
		&i.Genres,
		&i.Runtime,
		&i.Rating,
		&i.BackdropPath,
		&i.PosterPath,
		&i.MetadataProvider,
		&i.LastSearchAt,
		&i.MonitoringStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMovieFile = `-- name: UpdateMovieFile :one
UPDATE movie_files
SET quality = COALESCE($1, quality),
    format = COALESCE($2, format),
    media_info = COALESCE($3, media_info),
    file_date = COALESCE($4, file_date),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, movie_id, file_path, size, quality, format, media_info, file_date, date_added, created_at, updated_at, deleted_at
`

type UpdateMovieFileParams struct {
	Quality   sql.NullString        `json:"quality"`
	Format    sql.NullString        `json:"format"`
	MediaInfo pqtype.NullRawMessage `json:"media_info"`
	FileDate  sql.NullTime          `json:"file_date"`
	ID        string                `json:"id"`
}

func (q *Queries) UpdateMovieFile(ctx context.Context, arg UpdateMovieFileParams) (MovieFile, error) {
	row := q.db.QueryRowContext(ctx, updateMovieFile,
		arg.Quality,
		arg.Format,
		arg.MediaInfo,
		arg.FileDate,
		arg.ID,
	)
	var i MovieFile
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.FilePath,
		&i.Size,
		&i.Quality,
		&i.Format,
		&i.MediaInfo,
		&i.FileDate,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRootFolderFreeSpace = `-- name: UpdateRootFolderFreeSpace :exec
UPDATE root_folders
SET free_space = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateRootFolderFreeSpaceParams struct {
	FreeSpace int64  `json:"free_space"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateRootFolderFreeSpace(ctx context.Context, arg UpdateRootFolderFreeSpaceParams) error {
	_, err := q.db.ExecContext(ctx, updateRootFolderFreeSpace, arg.FreeSpace, arg.ID)
	return err
}

const updateRootFolderUnmappedCount = `-- name: UpdateRootFolderUnmappedCount :exec
UPDATE root_folders
SET unmapped_count = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateRootFolderUnmappedCountParams struct {
	UnmappedCount int32  `json:"unmapped_count"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateRootFolderUnmappedCount(ctx context.Context, arg UpdateRootFolderUnmappedCountParams) error {
	_, err := q.db.ExecContext(ctx, updateRootFolderUnmappedCount, arg.UnmappedCount, arg.ID)
	return err
}
