// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxies.sql

package dbpg

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createProxy = `-- name: CreateProxy :one
INSERT INTO proxies (id, kind, name, enabled, config_json, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, kind, name, enabled, config_json, created_at, updated_at
`

type CreateProxyParams struct {
	ID         string          `json:"id"`
	Kind       string          `json:"kind"`
	Name       string          `json:"name"`
	Enabled    bool            `json:"enabled"`
	ConfigJson json.RawMessage `json:"config_json"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, createProxy,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.ConfigJson,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProxy = `-- name: DeleteProxy :exec
DELETE FROM proxies WHERE id = $1
`

func (q *Queries) DeleteProxy(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProxy, id)
	return err
}

const getProxy = `-- name: GetProxy :one
SELECT id, kind, name, enabled, config_json, created_at, updated_at FROM proxies WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProxy(ctx context.Context, id string) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, getProxy, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndexerIDsByProxyID = `-- name: ListIndexerIDsByProxyID :many
SELECT id FROM indexers WHERE proxy_id = $1
`

func (q *Queries) ListIndexerIDsByProxyID(ctx context.Context, proxyID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIndexerIDsByProxyID, proxyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxies = `-- name: ListProxies :many
SELECT id, kind, name, enabled, config_json, created_at, updated_at FROM proxies ORDER BY name ASC
`

func (q *Queries) ListProxies(ctx context.Context) ([]Proxy, error) {
	rows, err := q.db.QueryContext(ctx, listProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchProxy = `-- name: PatchProxy :one
UPDATE proxies
SET kind        = COALESCE($1,        kind),
    name        = COALESCE($2,        name),
    enabled     = COALESCE($3,     enabled),
    config_json = COALESCE($4, config_json),
    updated_at  = NOW()
WHERE id = $5
RETURNING id, kind, name, enabled, config_json, created_at, updated_at
`

type PatchProxyParams struct {
	Kind       sql.NullString        `json:"kind"`
	Name       sql.NullString        `json:"name"`
	Enabled    sql.NullBool          `json:"enabled"`
	ConfigJson pqtype.NullRawMessage `json:"config_json"`
	ID         string                `json:"id"`
}

func (q *Queries) PatchProxy(ctx context.Context, arg PatchProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, patchProxy,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.ConfigJson,
		arg.ID,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceProxy = `-- name: ReplaceProxy :one
UPDATE proxies
SET kind        = $2,
    name        = $3,
    enabled     = $4,
    config_json = $5,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, kind, name, enabled, config_json, created_at, updated_at
`

type ReplaceProxyParams struct {
	ID         string          `json:"id"`
	Kind       string          `json:"kind"`
	Name       string          `json:"name"`
	Enabled    bool            `json:"enabled"`
	ConfigJson json.RawMessage `json:"config_json"`
}

func (q *Queries) ReplaceProxy(ctx context.Context, arg ReplaceProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, replaceProxy,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.ConfigJson,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
