// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbpg

import (
	"context"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAPIKeysForUser(ctx context.Context, userID int64) ([]ApiKey, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
}

var _ Querier = (*Queries)(nil)
