// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_meta.sql

package dbpg

import (
	"context"
)

const getSchemaMeta = `-- name: GetSchemaMeta :one
SELECT value FROM schema_meta WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSchemaMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSchemaMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setSchemaMeta = `-- name: SetSchemaMeta :exec
INSERT INTO schema_meta (key, value) VALUES ($1, $2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSchemaMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSchemaMeta(ctx context.Context, arg SetSchemaMetaParams) error {
	_, err := q.db.ExecContext(ctx, setSchemaMeta, arg.Key, arg.Value)
	return err
}
