// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package dbpg

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT id, name, schedule, last_run_at, next_run_at, paused, payload, created_at, updated_at, enabled, last_status, last_error FROM scheduled_jobs WHERE name = $1 LIMIT 1
`

func (q *Queries) GetScheduledJob(ctx context.Context, name string) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, getScheduledJob, name)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Paused,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.LastStatus,
		&i.LastError,
	)
	return i, err
}

const listScheduledJobs = `-- name: ListScheduledJobs :many
SELECT id, name, schedule, last_run_at, next_run_at, paused, payload, created_at, updated_at, enabled, last_status, last_error FROM scheduled_jobs ORDER BY name
`

func (q *Queries) ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Paused,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.LastStatus,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduledJobRun = `-- name: RecordScheduledJobRun :exec
UPDATE scheduled_jobs
SET last_run_at = $2,
    next_run_at = $3,
    last_status = $4,
    last_error  = $5,
    updated_at  = NOW()
WHERE name = $1
`

type RecordScheduledJobRunParams struct {
	Name       string       `json:"name"`
	LastRunAt  sql.NullTime `json:"last_run_at"`
	NextRunAt  sql.NullTime `json:"next_run_at"`
	LastStatus string       `json:"last_status"`
	LastError  string       `json:"last_error"`
}

func (q *Queries) RecordScheduledJobRun(ctx context.Context, arg RecordScheduledJobRunParams) error {
	_, err := q.db.ExecContext(ctx, recordScheduledJobRun,
		arg.Name,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.LastStatus,
		arg.LastError,
	)
	return err
}

const setScheduledJobEnabled = `-- name: SetScheduledJobEnabled :exec
UPDATE scheduled_jobs
SET enabled = $2, updated_at = NOW()
WHERE name = $1
`

type SetScheduledJobEnabledParams struct {
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetScheduledJobEnabled(ctx context.Context, arg SetScheduledJobEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setScheduledJobEnabled, arg.Name, arg.Enabled)
	return err
}

const setScheduledJobNextRun = `-- name: SetScheduledJobNextRun :exec
UPDATE scheduled_jobs
SET next_run_at = $2, updated_at = NOW()
WHERE name = $1
`

type SetScheduledJobNextRunParams struct {
	Name      string       `json:"name"`
	NextRunAt sql.NullTime `json:"next_run_at"`
}

func (q *Queries) SetScheduledJobNextRun(ctx context.Context, arg SetScheduledJobNextRunParams) error {
	_, err := q.db.ExecContext(ctx, setScheduledJobNextRun, arg.Name, arg.NextRunAt)
	return err
}

const upsertScheduledJob = `-- name: UpsertScheduledJob :one
INSERT INTO scheduled_jobs (name, schedule, payload, enabled, next_run_at)
VALUES ($1, $2, $3, TRUE, $4)
ON CONFLICT(name) DO UPDATE SET
    schedule   = EXCLUDED.schedule,
    payload    = EXCLUDED.payload,
    updated_at = NOW()
RETURNING id, name, schedule, last_run_at, next_run_at, paused, payload, created_at, updated_at, enabled, last_status, last_error
`

type UpsertScheduledJobParams struct {
	Name      string          `json:"name"`
	Schedule  string          `json:"schedule"`
	Payload   json.RawMessage `json:"payload"`
	NextRunAt sql.NullTime    `json:"next_run_at"`
}

func (q *Queries) UpsertScheduledJob(ctx context.Context, arg UpsertScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, upsertScheduledJob,
		arg.Name,
		arg.Schedule,
		arg.Payload,
		arg.NextRunAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Paused,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.LastStatus,
		&i.LastError,
	)
	return i, err
}
