// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sources.sql

package dbpg

import (
	"context"
	"database/sql"
)

const countUserSources = `-- name: CountUserSources :one
SELECT COUNT(*) FROM user_sources
`

func (q *Queries) CountUserSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserSource = `-- name: CreateUserSource :one
INSERT INTO user_sources (id, name, type, enabled, config, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, name, type, enabled, config, last_sync_at, created_at, updated_at
`

type CreateUserSourceParams struct {
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	Type    string       `json:"type"`
	Enabled sql.NullBool `json:"enabled"`
	Config  string       `json:"config"`
}

func (q *Queries) CreateUserSource(ctx context.Context, arg CreateUserSourceParams) (UserSource, error) {
	row := q.db.QueryRowContext(ctx, createUserSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Config,
	)
	var i UserSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSource = `-- name: DeleteUserSource :exec
DELETE FROM user_sources WHERE id = $1
`

func (q *Queries) DeleteUserSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSource, id)
	return err
}

const getUserSource = `-- name: GetUserSource :one
SELECT id, name, type, enabled, config, last_sync_at, created_at, updated_at FROM user_sources WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserSource(ctx context.Context, id string) (UserSource, error) {
	row := q.db.QueryRowContext(ctx, getUserSource, id)
	var i UserSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSourceByName = `-- name: GetUserSourceByName :one
SELECT id, name, type, enabled, config, last_sync_at, created_at, updated_at FROM user_sources WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserSourceByName(ctx context.Context, name string) (UserSource, error) {
	row := q.db.QueryRowContext(ctx, getUserSourceByName, name)
	var i UserSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledUserSources = `-- name: ListEnabledUserSources :many
SELECT id, name, type, enabled, config, last_sync_at, created_at, updated_at FROM user_sources WHERE enabled = true ORDER BY created_at DESC
`

func (q *Queries) ListEnabledUserSources(ctx context.Context) ([]UserSource, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledUserSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSource{}
	for rows.Next() {
		var i UserSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSources = `-- name: ListUserSources :many
SELECT id, name, type, enabled, config, last_sync_at, created_at, updated_at FROM user_sources ORDER BY created_at DESC
`

func (q *Queries) ListUserSources(ctx context.Context) ([]UserSource, error) {
	rows, err := q.db.QueryContext(ctx, listUserSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSource{}
	for rows.Next() {
		var i UserSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSourcesByType = `-- name: ListUserSourcesByType :many
SELECT id, name, type, enabled, config, last_sync_at, created_at, updated_at FROM user_sources WHERE type = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserSourcesByType(ctx context.Context, type_ string) ([]UserSource, error) {
	rows, err := q.db.QueryContext(ctx, listUserSourcesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSource{}
	for rows.Next() {
		var i UserSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchUserSource = `-- name: PatchUserSource :one
UPDATE user_sources
SET name        = COALESCE($1,    name),
    type        = COALESCE($2,    type),
    enabled     = COALESCE($3, enabled),
    config      = COALESCE($4,  config),
    updated_at  = NOW()
WHERE id = $5
RETURNING id, name, type, enabled, config, last_sync_at, created_at, updated_at
`

type PatchUserSourceParams struct {
	Name    sql.NullString `json:"name"`
	Type    sql.NullString `json:"type"`
	Enabled sql.NullBool   `json:"enabled"`
	Config  sql.NullString `json:"config"`
	ID      string         `json:"id"`
}

func (q *Queries) PatchUserSource(ctx context.Context, arg PatchUserSourceParams) (UserSource, error) {
	row := q.db.QueryRowContext(ctx, patchUserSource,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Config,
		arg.ID,
	)
	var i UserSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSource = `-- name: UpdateUserSource :one
UPDATE user_sources
SET name        = $2,
    type        = $3,
    enabled     = $4,
    config      = $5,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, type, enabled, config, last_sync_at, created_at, updated_at
`

type UpdateUserSourceParams struct {
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	Type    string       `json:"type"`
	Enabled sql.NullBool `json:"enabled"`
	Config  string       `json:"config"`
}

func (q *Queries) UpdateUserSource(ctx context.Context, arg UpdateUserSourceParams) (UserSource, error) {
	row := q.db.QueryRowContext(ctx, updateUserSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Config,
	)
	var i UserSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSourceLastSync = `-- name: UpdateUserSourceLastSync :one
UPDATE user_sources
SET last_sync_at = NOW()
WHERE id = $1
RETURNING id, name, type, enabled, config, last_sync_at, created_at, updated_at
`

func (q *Queries) UpdateUserSourceLastSync(ctx context.Context, id string) (UserSource, error) {
	row := q.db.QueryRowContext(ctx, updateUserSourceLastSync, id)
	var i UserSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
