-- +goose Up

-- bot_config holds the singleton configuration for the interactive request bots
-- (Telegram + Discord). A single row (id=1) stores the per-platform enablement
-- and tokens, plus the default quality-profile/library targets used when an
-- admin approves a request from chat (chat has no target picker like the web UI).
CREATE TABLE IF NOT EXISTS bot_config (
    id                                INTEGER PRIMARY KEY CHECK (id = 1),
    telegram_enabled                  BOOLEAN NOT NULL DEFAULT 0,
    telegram_bot_token                TEXT    NOT NULL DEFAULT '',
    discord_enabled                   BOOLEAN NOT NULL DEFAULT 0,
    discord_bot_token                 TEXT    NOT NULL DEFAULT '',
    default_movie_quality_profile_id  TEXT    NOT NULL DEFAULT '',
    default_movie_library_id          TEXT    NOT NULL DEFAULT '',
    default_series_quality_profile_id TEXT    NOT NULL DEFAULT '',
    default_series_library_id         TEXT    NOT NULL DEFAULT '',
    updated_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO bot_config (id) VALUES (1);

-- bot_account_links binds a chat identity (platform + external user id) to a Loom
-- user account. A chat identity maps to at most one Loom user per platform.
CREATE TABLE IF NOT EXISTS bot_account_links (
    id                TEXT      PRIMARY KEY,
    platform          TEXT      NOT NULL,
    external_id       TEXT      NOT NULL,
    external_username TEXT      NOT NULL DEFAULT '',
    user_id           INTEGER   NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (platform, external_id)
);

CREATE INDEX IF NOT EXISTS idx_bot_account_links_user
    ON bot_account_links (user_id);

-- bot_link_codes are short-lived, single-use codes generated by /link in chat and
-- redeemed by a logged-in user in the web UI to establish a binding. The code is
-- bound to the requesting chat identity so the web UI can show who is being linked.
CREATE TABLE IF NOT EXISTS bot_link_codes (
    code              TEXT      PRIMARY KEY,
    platform          TEXT      NOT NULL,
    external_id       TEXT      NOT NULL,
    external_username TEXT      NOT NULL DEFAULT '',
    expires_at        TIMESTAMP NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bot_link_codes_external
    ON bot_link_codes (platform, external_id);

-- +goose Down

DROP INDEX IF EXISTS idx_bot_link_codes_external;
DROP TABLE IF EXISTS bot_link_codes;
DROP INDEX IF EXISTS idx_bot_account_links_user;
DROP TABLE IF EXISTS bot_account_links;
DROP TABLE IF EXISTS bot_config;
