{{- if .Values.torrent.expose.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loom.fullname" . }}-torrent
  labels:
    {{- include "loom.labels" . | nindent 4 }}
  annotations:
    {{- if and (eq .Values.torrent.expose.type "LoadBalancer") .Values.torrent.expose.loadBalancerIP }}
    metallb.io/loadBalancerIPs: {{ .Values.torrent.expose.loadBalancerIP | quote }}
    {{- end }}
    {{- with .Values.torrent.expose.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.torrent.expose.type }}
  {{- if and (ne .Values.torrent.expose.type "ClusterIP") .Values.torrent.expose.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.torrent.expose.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: bt-tcp
      port: {{ .Values.torrent.listenPort }}
      targetPort: bt-tcp
      protocol: TCP
      {{- if and (eq .Values.torrent.expose.type "NodePort") (gt (int .Values.torrent.expose.nodePort) 0) }}
      nodePort: {{ .Values.torrent.expose.nodePort }}
      {{- end }}
    - name: bt-udp
      port: {{ .Values.torrent.listenPort }}
      targetPort: bt-udp
      protocol: UDP
      {{- if and (eq .Values.torrent.expose.type "NodePort") (gt (int .Values.torrent.expose.nodePortUdp) 0) }}
      nodePort: {{ .Values.torrent.expose.nodePortUdp }}
      {{- end }}
  selector:
    {{- include "loom.selectorLabels" . | nindent 4 }}
{{- end }}
