// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbsqlite

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash, prefix, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, key_hash, prefix, last_used_at, created_at, expires_at
`

type CreateAPIKeyParams struct {
	UserID    int64        `json:"user_id"`
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	Prefix    string       `json:"prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, prefix, last_used_at, created_at, expires_at FROM api_keys WHERE key_hash = ? LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, name, key_hash, prefix, last_used_at, created_at, expires_at FROM api_keys WHERE id = ? LIMIT 1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id int64) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, user_id, name, key_hash, prefix, last_used_at, created_at, expires_at FROM api_keys WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysForUser(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
DELETE FROM api_keys WHERE id = ? AND user_id = ?
`

type RevokeAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, id)
	return err
}
