// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_clients.sql

package dbsqlite

import (
	"context"
	"database/sql"
	"time"
)

const createDownloadClient = `-- name: CreateDownloadClient :one
INSERT INTO download_clients (
    id, name, kind, protocol, enabled, priority,
    host, port, tls, username, password,
    config_json,
    category_default, save_path_default,
    remove_completed, remove_failed,
    created_at, updated_at
)
VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?,
    ?, ?,
    ?, ?,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, name, kind, protocol, enabled, priority, host, port, tls, username, password, config_json, category_default, save_path_default, remove_completed, remove_failed, created_at, updated_at
`

type CreateDownloadClientParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	Protocol        string `json:"protocol"`
	Enabled         int64  `json:"enabled"`
	Priority        int64  `json:"priority"`
	Host            string `json:"host"`
	Port            int64  `json:"port"`
	Tls             int64  `json:"tls"`
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfigJson      string `json:"config_json"`
	CategoryDefault string `json:"category_default"`
	SavePathDefault string `json:"save_path_default"`
	RemoveCompleted int64  `json:"remove_completed"`
	RemoveFailed    int64  `json:"remove_failed"`
}

func (q *Queries) CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, createDownloadClient,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Protocol,
		arg.Enabled,
		arg.Priority,
		arg.Host,
		arg.Port,
		arg.Tls,
		arg.Username,
		arg.Password,
		arg.ConfigJson,
		arg.CategoryDefault,
		arg.SavePathDefault,
		arg.RemoveCompleted,
		arg.RemoveFailed,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Protocol,
		&i.Enabled,
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.Tls,
		&i.Username,
		&i.Password,
		&i.ConfigJson,
		&i.CategoryDefault,
		&i.SavePathDefault,
		&i.RemoveCompleted,
		&i.RemoveFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDownloadClient = `-- name: DeleteDownloadClient :exec
DELETE FROM download_clients WHERE id = ?
`

func (q *Queries) DeleteDownloadClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadClient, id)
	return err
}

const getDownloadClient = `-- name: GetDownloadClient :one
SELECT id, name, kind, protocol, enabled, priority, host, port, tls, username, password, config_json, category_default, save_path_default, remove_completed, remove_failed, created_at, updated_at FROM download_clients WHERE id = ? LIMIT 1
`

func (q *Queries) GetDownloadClient(ctx context.Context, id string) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, getDownloadClient, id)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Protocol,
		&i.Enabled,
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.Tls,
		&i.Username,
		&i.Password,
		&i.ConfigJson,
		&i.CategoryDefault,
		&i.SavePathDefault,
		&i.RemoveCompleted,
		&i.RemoveFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadClientHealth = `-- name: GetDownloadClientHealth :one
SELECT client_id, status, last_checked_at, last_success_at, last_failure_at, last_error, consecutive_failures, last_free_space_bytes, last_categories_json FROM download_client_health WHERE client_id = ? LIMIT 1
`

func (q *Queries) GetDownloadClientHealth(ctx context.Context, clientID string) (DownloadClientHealth, error) {
	row := q.db.QueryRowContext(ctx, getDownloadClientHealth, clientID)
	var i DownloadClientHealth
	err := row.Scan(
		&i.ClientID,
		&i.Status,
		&i.LastCheckedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.ConsecutiveFailures,
		&i.LastFreeSpaceBytes,
		&i.LastCategoriesJson,
	)
	return i, err
}

const listDownloadClientHealth = `-- name: ListDownloadClientHealth :many
SELECT client_id, status, last_checked_at, last_success_at, last_failure_at, last_error, consecutive_failures, last_free_space_bytes, last_categories_json FROM download_client_health
`

func (q *Queries) ListDownloadClientHealth(ctx context.Context) ([]DownloadClientHealth, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadClientHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClientHealth{}
	for rows.Next() {
		var i DownloadClientHealth
		if err := rows.Scan(
			&i.ClientID,
			&i.Status,
			&i.LastCheckedAt,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.LastFreeSpaceBytes,
			&i.LastCategoriesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadClients = `-- name: ListDownloadClients :many
SELECT id, name, kind, protocol, enabled, priority, host, port, tls, username, password, config_json, category_default, save_path_default, remove_completed, remove_failed, created_at, updated_at FROM download_clients ORDER BY priority ASC, name ASC
`

func (q *Queries) ListDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClient{}
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Protocol,
			&i.Enabled,
			&i.Priority,
			&i.Host,
			&i.Port,
			&i.Tls,
			&i.Username,
			&i.Password,
			&i.ConfigJson,
			&i.CategoryDefault,
			&i.SavePathDefault,
			&i.RemoveCompleted,
			&i.RemoveFailed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDownloadClients = `-- name: ListEnabledDownloadClients :many
SELECT id, name, kind, protocol, enabled, priority, host, port, tls, username, password, config_json, category_default, save_path_default, remove_completed, remove_failed, created_at, updated_at FROM download_clients WHERE enabled = 1 ORDER BY priority ASC, name ASC
`

func (q *Queries) ListEnabledDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClient{}
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Protocol,
			&i.Enabled,
			&i.Priority,
			&i.Host,
			&i.Port,
			&i.Tls,
			&i.Username,
			&i.Password,
			&i.ConfigJson,
			&i.CategoryDefault,
			&i.SavePathDefault,
			&i.RemoveCompleted,
			&i.RemoveFailed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchDownloadClient = `-- name: PatchDownloadClient :one
UPDATE download_clients
SET name              = COALESCE(?1, name),
    enabled           = COALESCE(?2, enabled),
    priority          = COALESCE(?3, priority),
    host              = COALESCE(?4, host),
    port              = COALESCE(?5, port),
    tls               = COALESCE(?6, tls),
    username          = COALESCE(?7, username),
    password          = COALESCE(?8, password),
    config_json       = COALESCE(?9, config_json),
    category_default  = COALESCE(?10, category_default),
    save_path_default = COALESCE(?11, save_path_default),
    remove_completed  = COALESCE(?12, remove_completed),
    remove_failed     = COALESCE(?13, remove_failed),
    updated_at        = CURRENT_TIMESTAMP
WHERE id = ?14
RETURNING id, name, kind, protocol, enabled, priority, host, port, tls, username, password, config_json, category_default, save_path_default, remove_completed, remove_failed, created_at, updated_at
`

type PatchDownloadClientParams struct {
	Name            sql.NullString `json:"name"`
	Enabled         sql.NullInt64  `json:"enabled"`
	Priority        sql.NullInt64  `json:"priority"`
	Host            sql.NullString `json:"host"`
	Port            sql.NullInt64  `json:"port"`
	Tls             sql.NullInt64  `json:"tls"`
	Username        sql.NullString `json:"username"`
	Password        sql.NullString `json:"password"`
	ConfigJson      sql.NullString `json:"config_json"`
	CategoryDefault sql.NullString `json:"category_default"`
	SavePathDefault sql.NullString `json:"save_path_default"`
	RemoveCompleted sql.NullInt64  `json:"remove_completed"`
	RemoveFailed    sql.NullInt64  `json:"remove_failed"`
	ID              string         `json:"id"`
}

func (q *Queries) PatchDownloadClient(ctx context.Context, arg PatchDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, patchDownloadClient,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.Host,
		arg.Port,
		arg.Tls,
		arg.Username,
		arg.Password,
		arg.ConfigJson,
		arg.CategoryDefault,
		arg.SavePathDefault,
		arg.RemoveCompleted,
		arg.RemoveFailed,
		arg.ID,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Protocol,
		&i.Enabled,
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.Tls,
		&i.Username,
		&i.Password,
		&i.ConfigJson,
		&i.CategoryDefault,
		&i.SavePathDefault,
		&i.RemoveCompleted,
		&i.RemoveFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceDownloadClient = `-- name: ReplaceDownloadClient :one
UPDATE download_clients
SET name              = ?,
    kind              = ?,
    protocol          = ?,
    enabled           = ?,
    priority          = ?,
    host              = ?,
    port              = ?,
    tls               = ?,
    username          = ?,
    password          = ?,
    config_json       = ?,
    category_default  = ?,
    save_path_default = ?,
    remove_completed  = ?,
    remove_failed     = ?,
    updated_at        = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, kind, protocol, enabled, priority, host, port, tls, username, password, config_json, category_default, save_path_default, remove_completed, remove_failed, created_at, updated_at
`

type ReplaceDownloadClientParams struct {
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	Protocol        string `json:"protocol"`
	Enabled         int64  `json:"enabled"`
	Priority        int64  `json:"priority"`
	Host            string `json:"host"`
	Port            int64  `json:"port"`
	Tls             int64  `json:"tls"`
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfigJson      string `json:"config_json"`
	CategoryDefault string `json:"category_default"`
	SavePathDefault string `json:"save_path_default"`
	RemoveCompleted int64  `json:"remove_completed"`
	RemoveFailed    int64  `json:"remove_failed"`
	ID              string `json:"id"`
}

func (q *Queries) ReplaceDownloadClient(ctx context.Context, arg ReplaceDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, replaceDownloadClient,
		arg.Name,
		arg.Kind,
		arg.Protocol,
		arg.Enabled,
		arg.Priority,
		arg.Host,
		arg.Port,
		arg.Tls,
		arg.Username,
		arg.Password,
		arg.ConfigJson,
		arg.CategoryDefault,
		arg.SavePathDefault,
		arg.RemoveCompleted,
		arg.RemoveFailed,
		arg.ID,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Protocol,
		&i.Enabled,
		&i.Priority,
		&i.Host,
		&i.Port,
		&i.Tls,
		&i.Username,
		&i.Password,
		&i.ConfigJson,
		&i.CategoryDefault,
		&i.SavePathDefault,
		&i.RemoveCompleted,
		&i.RemoveFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDownloadClientHealth = `-- name: UpsertDownloadClientHealth :exec
INSERT INTO download_client_health (
    client_id, status,
    last_checked_at, last_success_at, last_failure_at,
    last_error, consecutive_failures,
    last_free_space_bytes, last_categories_json
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(client_id) DO UPDATE SET
    status                = excluded.status,
    last_checked_at       = excluded.last_checked_at,
    last_success_at       = excluded.last_success_at,
    last_failure_at       = excluded.last_failure_at,
    last_error            = excluded.last_error,
    consecutive_failures  = excluded.consecutive_failures,
    last_free_space_bytes = excluded.last_free_space_bytes,
    last_categories_json  = excluded.last_categories_json
`

type UpsertDownloadClientHealthParams struct {
	ClientID            string        `json:"client_id"`
	Status              string        `json:"status"`
	LastCheckedAt       time.Time     `json:"last_checked_at"`
	LastSuccessAt       sql.NullTime  `json:"last_success_at"`
	LastFailureAt       sql.NullTime  `json:"last_failure_at"`
	LastError           string        `json:"last_error"`
	ConsecutiveFailures int64         `json:"consecutive_failures"`
	LastFreeSpaceBytes  sql.NullInt64 `json:"last_free_space_bytes"`
	LastCategoriesJson  string        `json:"last_categories_json"`
}

func (q *Queries) UpsertDownloadClientHealth(ctx context.Context, arg UpsertDownloadClientHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertDownloadClientHealth,
		arg.ClientID,
		arg.Status,
		arg.LastCheckedAt,
		arg.LastSuccessAt,
		arg.LastFailureAt,
		arg.LastError,
		arg.ConsecutiveFailures,
		arg.LastFreeSpaceBytes,
		arg.LastCategoriesJson,
	)
	return err
}
