// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer_caps_cache.sql

package dbsqlite

import (
	"context"
	"database/sql"
)

const getIndexerCapsCache = `-- name: GetIndexerCapsCache :one
SELECT last_caps_json
FROM   indexer_health
WHERE  indexer_id = ?
LIMIT  1
`

func (q *Queries) GetIndexerCapsCache(ctx context.Context, indexerID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getIndexerCapsCache, indexerID)
	var last_caps_json sql.NullString
	err := row.Scan(&last_caps_json)
	return last_caps_json, err
}

const updateIndexerCapsCache = `-- name: UpdateIndexerCapsCache :exec
UPDATE indexer_health
SET    last_caps_json = ?
WHERE  indexer_id     = ?
`

type UpdateIndexerCapsCacheParams struct {
	LastCapsJson sql.NullString `json:"last_caps_json"`
	IndexerID    string         `json:"indexer_id"`
}

func (q *Queries) UpdateIndexerCapsCache(ctx context.Context, arg UpdateIndexerCapsCacheParams) error {
	_, err := q.db.ExecContext(ctx, updateIndexerCapsCache, arg.LastCapsJson, arg.IndexerID)
	return err
}
