// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexers.sql

package dbsqlite

import (
	"context"
	"database/sql"
	"time"
)

const createIndexer = `-- name: CreateIndexer :one
INSERT INTO indexers (id, kind, name, enabled, priority, config_json, categories_json, tags_json, proxy_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, kind, name, enabled, priority, config_json, categories_json, tags_json, created_at, updated_at, proxy_id
`

type CreateIndexerParams struct {
	ID             string         `json:"id"`
	Kind           string         `json:"kind"`
	Name           string         `json:"name"`
	Enabled        int64          `json:"enabled"`
	Priority       int64          `json:"priority"`
	ConfigJson     string         `json:"config_json"`
	CategoriesJson string         `json:"categories_json"`
	TagsJson       string         `json:"tags_json"`
	ProxyID        sql.NullString `json:"proxy_id"`
}

func (q *Queries) CreateIndexer(ctx context.Context, arg CreateIndexerParams) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, createIndexer,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.ConfigJson,
		arg.CategoriesJson,
		arg.TagsJson,
		arg.ProxyID,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.ConfigJson,
		&i.CategoriesJson,
		&i.TagsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const deleteIndexer = `-- name: DeleteIndexer :exec
DELETE FROM indexers WHERE id = ?
`

func (q *Queries) DeleteIndexer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIndexer, id)
	return err
}

const getIndexer = `-- name: GetIndexer :one
SELECT id, kind, name, enabled, priority, config_json, categories_json, tags_json, created_at, updated_at, proxy_id FROM indexers WHERE id = ? LIMIT 1
`

func (q *Queries) GetIndexer(ctx context.Context, id string) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, getIndexer, id)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.ConfigJson,
		&i.CategoriesJson,
		&i.TagsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const getIndexerHealth = `-- name: GetIndexerHealth :one
SELECT indexer_id, status, last_checked_at, last_success_at, latency_ms, last_error, last_caps_json FROM indexer_health WHERE indexer_id = ? LIMIT 1
`

func (q *Queries) GetIndexerHealth(ctx context.Context, indexerID string) (IndexerHealth, error) {
	row := q.db.QueryRowContext(ctx, getIndexerHealth, indexerID)
	var i IndexerHealth
	err := row.Scan(
		&i.IndexerID,
		&i.Status,
		&i.LastCheckedAt,
		&i.LastSuccessAt,
		&i.LatencyMs,
		&i.LastError,
		&i.LastCapsJson,
	)
	return i, err
}

const listEnabledIndexers = `-- name: ListEnabledIndexers :many
SELECT id, kind, name, enabled, priority, config_json, categories_json, tags_json, created_at, updated_at, proxy_id FROM indexers WHERE enabled = 1 ORDER BY priority ASC, name ASC
`

func (q *Queries) ListEnabledIndexers(ctx context.Context) ([]Indexer, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIndexers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indexer{}
	for rows.Next() {
		var i Indexer
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.ConfigJson,
			&i.CategoriesJson,
			&i.TagsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProxyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexerHealth = `-- name: ListIndexerHealth :many
SELECT indexer_id, status, last_checked_at, last_success_at, latency_ms, last_error, last_caps_json FROM indexer_health
`

func (q *Queries) ListIndexerHealth(ctx context.Context) ([]IndexerHealth, error) {
	rows, err := q.db.QueryContext(ctx, listIndexerHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexerHealth{}
	for rows.Next() {
		var i IndexerHealth
		if err := rows.Scan(
			&i.IndexerID,
			&i.Status,
			&i.LastCheckedAt,
			&i.LastSuccessAt,
			&i.LatencyMs,
			&i.LastError,
			&i.LastCapsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexers = `-- name: ListIndexers :many
SELECT id, kind, name, enabled, priority, config_json, categories_json, tags_json, created_at, updated_at, proxy_id FROM indexers ORDER BY priority ASC, name ASC
`

func (q *Queries) ListIndexers(ctx context.Context) ([]Indexer, error) {
	rows, err := q.db.QueryContext(ctx, listIndexers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indexer{}
	for rows.Next() {
		var i Indexer
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.ConfigJson,
			&i.CategoriesJson,
			&i.TagsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProxyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchIndexer = `-- name: PatchIndexer :one
UPDATE indexers
SET name      = COALESCE(?1, name),
    enabled   = COALESCE(?2, enabled),
    priority  = COALESCE(?3, priority),
    tags_json = COALESCE(?4, tags_json),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
RETURNING id, kind, name, enabled, priority, config_json, categories_json, tags_json, created_at, updated_at, proxy_id
`

type PatchIndexerParams struct {
	Name     sql.NullString `json:"name"`
	Enabled  sql.NullInt64  `json:"enabled"`
	Priority sql.NullInt64  `json:"priority"`
	TagsJson sql.NullString `json:"tags_json"`
	ID       string         `json:"id"`
}

func (q *Queries) PatchIndexer(ctx context.Context, arg PatchIndexerParams) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, patchIndexer,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.TagsJson,
		arg.ID,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.ConfigJson,
		&i.CategoriesJson,
		&i.TagsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const replaceIndexer = `-- name: ReplaceIndexer :one
UPDATE indexers
SET kind            = ?,
    name            = ?,
    enabled         = ?,
    priority        = ?,
    config_json     = ?,
    categories_json = ?,
    tags_json       = ?,
    proxy_id        = ?,
    updated_at      = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, kind, name, enabled, priority, config_json, categories_json, tags_json, created_at, updated_at, proxy_id
`

type ReplaceIndexerParams struct {
	Kind           string         `json:"kind"`
	Name           string         `json:"name"`
	Enabled        int64          `json:"enabled"`
	Priority       int64          `json:"priority"`
	ConfigJson     string         `json:"config_json"`
	CategoriesJson string         `json:"categories_json"`
	TagsJson       string         `json:"tags_json"`
	ProxyID        sql.NullString `json:"proxy_id"`
	ID             string         `json:"id"`
}

func (q *Queries) ReplaceIndexer(ctx context.Context, arg ReplaceIndexerParams) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, replaceIndexer,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.ConfigJson,
		arg.CategoriesJson,
		arg.TagsJson,
		arg.ProxyID,
		arg.ID,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.ConfigJson,
		&i.CategoriesJson,
		&i.TagsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const setIndexerProxyID = `-- name: SetIndexerProxyID :exec
UPDATE indexers
SET proxy_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetIndexerProxyIDParams struct {
	ProxyID sql.NullString `json:"proxy_id"`
	ID      string         `json:"id"`
}

// Used by PATCH /api/v1/indexers/{id} to attach (or clear, when the
// value is NULL) a proxy. We can't fold this into PatchIndexer with
// COALESCE alone because "no change" and "explicit clear" need to be
// distinguishable, and our other patch fields use COALESCE-on-NULL.
func (q *Queries) SetIndexerProxyID(ctx context.Context, arg SetIndexerProxyIDParams) error {
	_, err := q.db.ExecContext(ctx, setIndexerProxyID, arg.ProxyID, arg.ID)
	return err
}

const upsertIndexerHealth = `-- name: UpsertIndexerHealth :exec
INSERT INTO indexer_health (indexer_id, status, last_checked_at, last_success_at, latency_ms, last_error)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(indexer_id) DO UPDATE SET
    status          = excluded.status,
    last_checked_at = excluded.last_checked_at,
    last_success_at = excluded.last_success_at,
    latency_ms      = excluded.latency_ms,
    last_error      = excluded.last_error
`

type UpsertIndexerHealthParams struct {
	IndexerID     string        `json:"indexer_id"`
	Status        string        `json:"status"`
	LastCheckedAt time.Time     `json:"last_checked_at"`
	LastSuccessAt sql.NullTime  `json:"last_success_at"`
	LatencyMs     sql.NullInt64 `json:"latency_ms"`
	LastError     string        `json:"last_error"`
}

func (q *Queries) UpsertIndexerHealth(ctx context.Context, arg UpsertIndexerHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertIndexerHealth,
		arg.IndexerID,
		arg.Status,
		arg.LastCheckedAt,
		arg.LastSuccessAt,
		arg.LatencyMs,
		arg.LastError,
	)
	return err
}
