// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlite

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Prefix     string       `json:"prefix"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type DownloadClient struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Kind            string    `json:"kind"`
	Protocol        string    `json:"protocol"`
	Enabled         int64     `json:"enabled"`
	Priority        int64     `json:"priority"`
	Host            string    `json:"host"`
	Port            int64     `json:"port"`
	Tls             int64     `json:"tls"`
	Username        string    `json:"username"`
	Password        string    `json:"password"`
	ConfigJson      string    `json:"config_json"`
	CategoryDefault string    `json:"category_default"`
	SavePathDefault string    `json:"save_path_default"`
	RemoveCompleted int64     `json:"remove_completed"`
	RemoveFailed    int64     `json:"remove_failed"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type DownloadClientHealth struct {
	ClientID            string        `json:"client_id"`
	Status              string        `json:"status"`
	LastCheckedAt       time.Time     `json:"last_checked_at"`
	LastSuccessAt       sql.NullTime  `json:"last_success_at"`
	LastFailureAt       sql.NullTime  `json:"last_failure_at"`
	LastError           string        `json:"last_error"`
	ConsecutiveFailures int64         `json:"consecutive_failures"`
	LastFreeSpaceBytes  sql.NullInt64 `json:"last_free_space_bytes"`
	LastCategoriesJson  string        `json:"last_categories_json"`
}

type Indexer struct {
	ID               string         `json:"id"`
	Kind             string         `json:"kind"`
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	Priority         int64          `json:"priority"`
	ConfigJson       string         `json:"config_json"`
	CategoriesJson   string         `json:"categories_json"`
	TagsJson         string         `json:"tags_json"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ProxyID          sql.NullString `json:"proxy_id"`
	RateLimitPerMin  sql.NullInt64  `json:"rate_limit_per_min"`
	RateLimitBurst   sql.NullInt64  `json:"rate_limit_burst"`
	RetryMaxAttempts sql.NullInt64  `json:"retry_max_attempts"`
}

type IndexerHealth struct {
	IndexerID     string         `json:"indexer_id"`
	Status        string         `json:"status"`
	LastCheckedAt time.Time      `json:"last_checked_at"`
	LastSuccessAt sql.NullTime   `json:"last_success_at"`
	LatencyMs     sql.NullInt64  `json:"latency_ms"`
	LastError     string         `json:"last_error"`
	LastCapsJson  sql.NullString `json:"last_caps_json"`
}

type Proxy struct {
	ID         string    `json:"id"`
	Kind       string    `json:"kind"`
	Name       string    `json:"name"`
	Enabled    int64     `json:"enabled"`
	ConfigJson string    `json:"config_json"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ScheduledJob struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Schedule   string       `json:"schedule"`
	LastRunAt  sql.NullTime `json:"last_run_at"`
	NextRunAt  sql.NullTime `json:"next_run_at"`
	Paused     int64        `json:"paused"`
	Payload    string       `json:"payload"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Enabled    int64        `json:"enabled"`
	LastStatus string       `json:"last_status"`
	LastError  string       `json:"last_error"`
}

type SchemaMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	Role         string         `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
