// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlite

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Prefix     string       `json:"prefix"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type DownloadClient struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Kind            string    `json:"kind"`
	Protocol        string    `json:"protocol"`
	Enabled         int64     `json:"enabled"`
	Priority        int64     `json:"priority"`
	Host            string    `json:"host"`
	Port            int64     `json:"port"`
	Tls             int64     `json:"tls"`
	Username        string    `json:"username"`
	Password        string    `json:"password"`
	ConfigJson      string    `json:"config_json"`
	CategoryDefault string    `json:"category_default"`
	SavePathDefault string    `json:"save_path_default"`
	RemoveCompleted int64     `json:"remove_completed"`
	RemoveFailed    int64     `json:"remove_failed"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type DownloadClientHealth struct {
	ClientID            string        `json:"client_id"`
	Status              string        `json:"status"`
	LastCheckedAt       time.Time     `json:"last_checked_at"`
	LastSuccessAt       sql.NullTime  `json:"last_success_at"`
	LastFailureAt       sql.NullTime  `json:"last_failure_at"`
	LastError           string        `json:"last_error"`
	ConsecutiveFailures int64         `json:"consecutive_failures"`
	LastFreeSpaceBytes  sql.NullInt64 `json:"last_free_space_bytes"`
	LastCategoriesJson  string        `json:"last_categories_json"`
}

type Indexer struct {
	ID               string         `json:"id"`
	Kind             string         `json:"kind"`
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	Priority         int64          `json:"priority"`
	ConfigJson       string         `json:"config_json"`
	CategoriesJson   string         `json:"categories_json"`
	TagsJson         string         `json:"tags_json"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ProxyID          sql.NullString `json:"proxy_id"`
	RateLimitPerMin  sql.NullInt64  `json:"rate_limit_per_min"`
	RateLimitBurst   sql.NullInt64  `json:"rate_limit_burst"`
	RetryMaxAttempts sql.NullInt64  `json:"retry_max_attempts"`
}

type IndexerHealth struct {
	IndexerID     string         `json:"indexer_id"`
	Status        string         `json:"status"`
	LastCheckedAt time.Time      `json:"last_checked_at"`
	LastSuccessAt sql.NullTime   `json:"last_success_at"`
	LatencyMs     sql.NullInt64  `json:"latency_ms"`
	LastError     string         `json:"last_error"`
	LastCapsJson  sql.NullString `json:"last_caps_json"`
}

type MetadataEpisode struct {
	ID         string         `json:"id"`
	SeriesID   string         `json:"series_id"`
	Season     int64          `json:"season"`
	Episode    int64          `json:"episode"`
	TvdbID     sql.NullString `json:"tvdb_id"`
	TmdbID     sql.NullString `json:"tmdb_id"`
	Title      string         `json:"title"`
	Overview   string         `json:"overview"`
	AirDate    string         `json:"air_date"`
	Runtime    int64          `json:"runtime"`
	Rating     float64        `json:"rating"`
	CachedJson string         `json:"cached_json"`
	CachedAt   time.Time      `json:"cached_at"`
	ExpiresAt  time.Time      `json:"expires_at"`
}

type MetadataMovie struct {
	ID          string         `json:"id"`
	TmdbID      sql.NullString `json:"tmdb_id"`
	ImdbID      sql.NullString `json:"imdb_id"`
	TvdbID      sql.NullString `json:"tvdb_id"`
	Title       string         `json:"title"`
	Year        sql.NullInt64  `json:"year"`
	Overview    string         `json:"overview"`
	PosterPath  string         `json:"poster_path"`
	ReleaseDate string         `json:"release_date"`
	Runtime     int64          `json:"runtime"`
	Genres      string         `json:"genres"`
	Rating      float64        `json:"rating"`
	CachedJson  string         `json:"cached_json"`
	CachedAt    time.Time      `json:"cached_at"`
	ExpiresAt   time.Time      `json:"expires_at"`
}

type MetadataSeries struct {
	ID           string         `json:"id"`
	TmdbID       sql.NullString `json:"tmdb_id"`
	ImdbID       sql.NullString `json:"imdb_id"`
	TvdbID       sql.NullString `json:"tvdb_id"`
	Title        string         `json:"title"`
	Overview     string         `json:"overview"`
	PosterPath   string         `json:"poster_path"`
	FirstAirDate string         `json:"first_air_date"`
	Genres       string         `json:"genres"`
	Rating       float64        `json:"rating"`
	Seasons      int64          `json:"seasons"`
	CachedJson   string         `json:"cached_json"`
	CachedAt     time.Time      `json:"cached_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

type Movie struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	Year             int64          `json:"year"`
	ImdbID           sql.NullString `json:"imdb_id"`
	TmdbID           sql.NullString `json:"tmdb_id"`
	TvdbID           sql.NullString `json:"tvdb_id"`
	Overview         string         `json:"overview"`
	Genres           string         `json:"genres"`
	Runtime          int64          `json:"runtime"`
	Rating           float64        `json:"rating"`
	BackdropPath     string         `json:"backdrop_path"`
	PosterPath       string         `json:"poster_path"`
	MetadataProvider string         `json:"metadata_provider"`
	LastSearchAt     sql.NullTime   `json:"last_search_at"`
	MonitoringStatus string         `json:"monitoring_status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type MovieFile struct {
	ID        string       `json:"id"`
	MovieID   string       `json:"movie_id"`
	FilePath  string       `json:"file_path"`
	Size      int64        `json:"size"`
	Quality   string       `json:"quality"`
	Format    string       `json:"format"`
	MediaInfo string       `json:"media_info"`
	FileDate  sql.NullTime `json:"file_date"`
	DateAdded time.Time    `json:"date_added"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Proxy struct {
	ID         string    `json:"id"`
	Kind       string    `json:"kind"`
	Name       string    `json:"name"`
	Enabled    int64     `json:"enabled"`
	ConfigJson string    `json:"config_json"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RootFolder struct {
	ID            string       `json:"id"`
	Path          string       `json:"path"`
	FreeSpace     int64        `json:"free_space"`
	UnmappedCount int64        `json:"unmapped_count"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type RssItem struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Link        sql.NullString `json:"link"`
	PublishedAt sql.NullTime   `json:"published_at"`
	SourceID    string         `json:"source_id"`
	Guid        string         `json:"guid"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	Raw         sql.NullString `json:"raw"`
}

type ScheduledJob struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Schedule   string       `json:"schedule"`
	LastRunAt  sql.NullTime `json:"last_run_at"`
	NextRunAt  sql.NullTime `json:"next_run_at"`
	Paused     int64        `json:"paused"`
	Payload    string       `json:"payload"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Enabled    int64        `json:"enabled"`
	LastStatus string       `json:"last_status"`
	LastError  string       `json:"last_error"`
}

type SchemaMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	Role         string         `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type UserSource struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Type       string       `json:"type"`
	Enabled    sql.NullBool `json:"enabled"`
	Config     string       `json:"config"`
	LastSyncAt sql.NullTime `json:"last_sync_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
