// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlite

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error)
	CreateIndexer(ctx context.Context, arg CreateIndexerParams) (Indexer, error)
	CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDownloadClient(ctx context.Context, id string) error
	DeleteIndexer(ctx context.Context, id string) error
	DeleteProxy(ctx context.Context, id string) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id int64) (ApiKey, error)
	GetDownloadClient(ctx context.Context, id string) (DownloadClient, error)
	GetDownloadClientHealth(ctx context.Context, clientID string) (DownloadClientHealth, error)
	GetIndexer(ctx context.Context, id string) (Indexer, error)
	GetIndexerCapsCache(ctx context.Context, indexerID string) (sql.NullString, error)
	GetIndexerHealth(ctx context.Context, indexerID string) (IndexerHealth, error)
	GetProxy(ctx context.Context, id string) (Proxy, error)
	GetScheduledJob(ctx context.Context, name string) (ScheduledJob, error)
	GetSchemaMeta(ctx context.Context, key string) (string, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAPIKeysForUser(ctx context.Context, userID int64) ([]ApiKey, error)
	ListDownloadClientHealth(ctx context.Context) ([]DownloadClientHealth, error)
	ListDownloadClients(ctx context.Context) ([]DownloadClient, error)
	ListEnabledDownloadClients(ctx context.Context) ([]DownloadClient, error)
	ListEnabledIndexers(ctx context.Context) ([]Indexer, error)
	ListIndexerHealth(ctx context.Context) ([]IndexerHealth, error)
	ListIndexerIDsByProxyID(ctx context.Context, proxyID sql.NullString) ([]string, error)
	ListIndexers(ctx context.Context) ([]Indexer, error)
	ListProxies(ctx context.Context) ([]Proxy, error)
	ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error)
	PatchDownloadClient(ctx context.Context, arg PatchDownloadClientParams) (DownloadClient, error)
	PatchIndexer(ctx context.Context, arg PatchIndexerParams) (Indexer, error)
	PatchProxy(ctx context.Context, arg PatchProxyParams) (Proxy, error)
	RecordScheduledJobRun(ctx context.Context, arg RecordScheduledJobRunParams) error
	ReplaceDownloadClient(ctx context.Context, arg ReplaceDownloadClientParams) (DownloadClient, error)
	ReplaceIndexer(ctx context.Context, arg ReplaceIndexerParams) (Indexer, error)
	ReplaceProxy(ctx context.Context, arg ReplaceProxyParams) (Proxy, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	// Used by PATCH /api/v1/indexers/{id} to attach (or clear, when the
	// value is NULL) a proxy. We can't fold this into PatchIndexer with
	// COALESCE alone because "no change" and "explicit clear" need to be
	// distinguishable, and our other patch fields use COALESCE-on-NULL.
	SetIndexerProxyID(ctx context.Context, arg SetIndexerProxyIDParams) error
	// Phase 2f: write the three rate-limit dials atomically. NULLs mean
	// "fall back to the package default at runtime". Used by POST/PUT
	// handlers and by the rate-limit PATCH path.
	SetIndexerRateLimit(ctx context.Context, arg SetIndexerRateLimitParams) error
	SetScheduledJobEnabled(ctx context.Context, arg SetScheduledJobEnabledParams) error
	SetScheduledJobNextRun(ctx context.Context, arg SetScheduledJobNextRunParams) error
	SetSchemaMeta(ctx context.Context, arg SetSchemaMetaParams) error
	TouchAPIKey(ctx context.Context, id int64) error
	UpdateIndexerCapsCache(ctx context.Context, arg UpdateIndexerCapsCacheParams) error
	UpdateUserOIDC(ctx context.Context, arg UpdateUserOIDCParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertDownloadClientHealth(ctx context.Context, arg UpsertDownloadClientHealthParams) error
	UpsertIndexerHealth(ctx context.Context, arg UpsertIndexerHealthParams) error
	// Inserts a job row on first registration; on conflict (same name) only
	// the schedule and payload are refreshed so callers can change cron
	// expressions in code without manual intervention. Run-status fields
	// (last_run_at, last_status, last_error, next_run_at) are preserved.
	UpsertScheduledJob(ctx context.Context, arg UpsertScheduledJobParams) (ScheduledJob, error)
}

var _ Querier = (*Queries)(nil)
