// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package dbsqlite

import (
	"context"
	"database/sql"
)

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT id, name, schedule, last_run_at, next_run_at, paused, payload, created_at, updated_at, enabled, last_status, last_error FROM scheduled_jobs WHERE name = ? LIMIT 1
`

func (q *Queries) GetScheduledJob(ctx context.Context, name string) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, getScheduledJob, name)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Paused,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.LastStatus,
		&i.LastError,
	)
	return i, err
}

const listScheduledJobs = `-- name: ListScheduledJobs :many
SELECT id, name, schedule, last_run_at, next_run_at, paused, payload, created_at, updated_at, enabled, last_status, last_error FROM scheduled_jobs ORDER BY name
`

func (q *Queries) ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Paused,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.LastStatus,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduledJobRun = `-- name: RecordScheduledJobRun :exec
UPDATE scheduled_jobs
SET last_run_at = ?,
    next_run_at = ?,
    last_status = ?,
    last_error  = ?,
    updated_at  = CURRENT_TIMESTAMP
WHERE name = ?
`

type RecordScheduledJobRunParams struct {
	LastRunAt  sql.NullTime `json:"last_run_at"`
	NextRunAt  sql.NullTime `json:"next_run_at"`
	LastStatus string       `json:"last_status"`
	LastError  string       `json:"last_error"`
	Name       string       `json:"name"`
}

func (q *Queries) RecordScheduledJobRun(ctx context.Context, arg RecordScheduledJobRunParams) error {
	_, err := q.db.ExecContext(ctx, recordScheduledJobRun,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.LastStatus,
		arg.LastError,
		arg.Name,
	)
	return err
}

const setScheduledJobEnabled = `-- name: SetScheduledJobEnabled :exec
UPDATE scheduled_jobs
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE name = ?
`

type SetScheduledJobEnabledParams struct {
	Enabled int64  `json:"enabled"`
	Name    string `json:"name"`
}

func (q *Queries) SetScheduledJobEnabled(ctx context.Context, arg SetScheduledJobEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setScheduledJobEnabled, arg.Enabled, arg.Name)
	return err
}

const setScheduledJobNextRun = `-- name: SetScheduledJobNextRun :exec
UPDATE scheduled_jobs
SET next_run_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE name = ?
`

type SetScheduledJobNextRunParams struct {
	NextRunAt sql.NullTime `json:"next_run_at"`
	Name      string       `json:"name"`
}

func (q *Queries) SetScheduledJobNextRun(ctx context.Context, arg SetScheduledJobNextRunParams) error {
	_, err := q.db.ExecContext(ctx, setScheduledJobNextRun, arg.NextRunAt, arg.Name)
	return err
}

const upsertScheduledJob = `-- name: UpsertScheduledJob :one
INSERT INTO scheduled_jobs (name, schedule, payload, enabled, next_run_at)
VALUES (?, ?, ?, 1, ?)
ON CONFLICT(name) DO UPDATE SET
    schedule   = excluded.schedule,
    payload    = excluded.payload,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, schedule, last_run_at, next_run_at, paused, payload, created_at, updated_at, enabled, last_status, last_error
`

type UpsertScheduledJobParams struct {
	Name      string       `json:"name"`
	Schedule  string       `json:"schedule"`
	Payload   string       `json:"payload"`
	NextRunAt sql.NullTime `json:"next_run_at"`
}

// Inserts a job row on first registration; on conflict (same name) only
// the schedule and payload are refreshed so callers can change cron
// expressions in code without manual intervention. Run-status fields
// (last_run_at, last_status, last_error, next_run_at) are preserved.
func (q *Queries) UpsertScheduledJob(ctx context.Context, arg UpsertScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, upsertScheduledJob,
		arg.Name,
		arg.Schedule,
		arg.Payload,
		arg.NextRunAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Paused,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.LastStatus,
		&i.LastError,
	)
	return i, err
}
